# Generated by Django 4.1.3 on 2022-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='data_nascimento',
            new_name='data_nascimento_aluno',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='nome_aluno',
        ),
        migrations.RenameField(
            model_name='assunto',
            old_name='nome',
            new_name='nome_assunto',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='data_nascimento',
            new_name='data_nascimento_professor',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='nome',
            new_name='nome_professor',
        ),
        migrations.RenameField(
            model_name='sentimentos',
            old_name='nome',
            new_name='nome_sentimentos',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='genero',
        ),
        migrations.AddField(
            model_name='aluno',
            name='genero_aluno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='genero_professor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
